### ISSUE TITLE
error

### ISSUE THREAD

**Issue by marfha88** [microsoft/vscode-azureAutomation#22]
Does this occur consistently? 
Repro steps:

1.
2.

Action: automation.openLocal
Error type: ENOENT
Error Message: ENOENT: no such file or directory, open 'c:\Program Files\Microsoft VS Code//vscodeAutomation//redacted:id//role-pim-expiry-checker.ps1'

Version: 1.1.0
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.75.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.js:2:1676472extension.js:2:1676472
n extension.js:2:1669894
```

</details>

**Comment by zb-creativeone** [comment]
You can set the working directory for the Azure Automation extension to use in either the extensions settings ( **ctrl + ,** -> **Extensions** -> **Azure Automation** › **Directory: Base Path** ) or the workspace settings ( **.vscode** -> **settings.json** -> `"azureAutomation.directory.basePath"` ).  If you do not set either, then the extension uses C:\Program Files\Microsoft VS Code as the working directory.  Try specifying a base path that you create in your user directory.

**Comment by Kapilhk** [comment]
Hi @marfha88 , was this resolved by as suggested in above comment?

**Comment by enthusol** [comment]
Is it possible to automaticly define the active project/workspace path instead of manually set this setting per workspace? I thought about setting an universal value in the extension settings ("Directory: Base Path") but I did not get it working.

**Comment by Shruti-MS** [comment]
@marfha88 This issue has been resolved in beta version: can be installed as pre-release from marketplace. Do share feedback on marketplace or reopen issue if problem persists. The beta version be pushed as default by next week.
