### ISSUE TITLE
Unable to upload draft after period of time

### ISSUE THREAD

**Issue by carlin-q-scott** [microsoft/vscode-azureAutomation#24]
Does this occur consistently? No
Repro steps:

1. Open a runbook for editing
2. Modify it
3. Upload draft
4. Publish
5. Run it
6. Edit some more
7. Upload draft
8. Encounter 401 error

Action: automation.saveAsDraft
Error type: Error
Error Message: Request failed with status code 401

Version: 1.1.0
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.76.2
Language: en

<details>
<summary>Call Stack</summary>

```
e.exports extension.js:2:1340252
e.exports extension.js:2:1342668
IncomingMessage.<anonymous> extension.js:2:1333305
```

</details>

## Additional Information

I was able to fetch the runbook, and open other runbooks. Only upload draft was getting a 401 error. I was able to resolve the issue by closing and re-opening VS Code. So I'm wondering if the access token permissions changed. I checked the extension output window and no additional detail about the error was there.

**Comment by carlin-q-scott** [comment]
Thank you @Kapilhk . That's a much better workaround than the one I used!

**Comment by Shruti-MS** [comment]
@carlin-q-scott  This issue has been resolved in beta version: can be installed as pre-release from marketplace. Do share feedback on marketplace or reopen issue if problem persists. The beta version be pushed as default by next week.
