### ISSUE TITLE
Track Output is buggy

### ISSUE THREAD

**Issue by carlin-q-scott** [microsoft/vscode-azureAutomation#25]
When I track output, it shows queued, and then once the job starts, the output goes blank for the rest of the life of the job. I'm never updated on the status of the job after the queued state.

**Comment by Kapilhk** [comment]
Hi @carlin-q-scott , It would be great if you could share insights on this particular job. Did it complete successfully as shown on Portal? Did the job have any runtime exceptions?

Also is it possible to repro or transient? Please share repro steps

**Comment by carlin-q-scott** [comment]
It happened every time I used this feature. It didn't matter if the job succeeded or failed. Maybe it's related to the access token expiration issue I reported in #24.
