### ISSUE TITLE
Error: The subscription '{id}' could not be found.

### ISSUE THREAD

**Issue by uRsIoNceNEdO** [microsoft/vscode-azureAutomation#27]
1. Our subscription is in the Azure Government environment, specifically GCC High.
2. My account is an Owner on the subscription.
3. Other VS Code extensions for Azure work fine, e.g. API Management and Resources.

**Comment by Shruti-MS** [comment]
@uRsIoNceNEdO, can you please at which step this error occurs while loading subscriptions or loading automation accounts under tree?
There can be error in authentication with Gov Cloud.

Thanks

**Comment by Shruti-MS** [comment]
@uRsIoNceNEdO  This issue has been resolved in beta version: can be installed as pre-release from marketplace. Do share feedback on marketplace or reopen issue if problem persists. The beta version be pushed as default by next week.
