### ISSUE TITLE
Create Runbook fails with status code 401

### ISSUE THREAD

**Issue by PeterJamesLawson** [microsoft/vscode-azureAutomation#34]
Does this occur consistently? Yes
Repro steps:

1. Sign in to azure
2. Select subscription
3. Go to Automation account
4. Right click on Runbooks --> Create Runbook
5. Provide name
6. Select Runbook type

Action: automation.createRunbook
Error type: Error
Error Message: Request failed with status code 401

Version: 1.1.0
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.77.3
Language: en

<details>
<summary>Call Stack</summary>

```
e.exports extension.js:2:1340252
e.exports extension.js:2:1342668
IncomingMessage.<anonymous> extension.js:2:1333305
```

</details>

**Comment by Shruti-MS** [comment]
@PeterJamesLawson  This issue has been resolved in beta version: can be installed as pre-release from marketplace. Do share feedback on marketplace or reopen issue if problem persists. The beta version be pushed as default by next week.
