### ISSUE TITLE
Cannot reliably publish workbooks because of "Error 401" 

### ISSUE THREAD

**Issue by nicoladelvacchio** [microsoft/vscode-azureAutomation#37]
Does this occur consistently? 
Not sure, it works for a while and at a certain point I get "Error 401" trying to publish. 
Repro steps:
1. Fetch Runbook, either Draft or Published
2. Change code
3. Select Upload as Published, sometimes works sometimes it doesn't

Action: automation.publishRunbook
Error type: Error
Error Message: Request failed with status code 401

Version: 1.1.0
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.78.2
Language: en

<details>
<summary>Call Stack</summary>

```
e.exports extension.js:2:1340252
e.exports extension.js:2:1342668
IncomingMessage.<anonymous> extension.js:2:1333305
```

</details>

**Comment by nicoladelvacchio** [comment]
Restarting vscode would fix the issue for a while

**Comment by Shruti-MS** [comment]
@nicoladelvacchio Please use the following simple workaround:

Try clicking on another Automation Account in left tree view and the return back to current account and attempt the save/publish.

We will be publishing the fix in next versions.
