### ISSUE TITLE
automation.publishRunbook

### ISSUE THREAD

**Issue by Lodbrockcraft** [microsoft/vscode-azureAutomation#55]
Does this occur consistently? 
Repro steps:

1.
2.

Action: automation.publishRunbook
Error type: Error
Error Message: Request failed with status code 403

Version: 1.2.2
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.84.2
Language: pt-br

<details>
<summary>Call Stack</summary>

```
e.exports extension.js:2:1340252
e.exports extension.js:2:1342668
IncomingMessage.<anonymous> extension.js:2:1333305
```

</details>

**Comment by Shruti-MS** [comment]
@Lodbrockcraft  From the response , you are forbidden to perform publish operation to runbook.
Can you please confirm if you are able to publish runbook from portal. If so please provide the Extension version you are using and confirm error is transient or permanent?

**Comment by Shruti-MS** [comment]
Did not get response from long time, Please reopen the issue if have any queries.
