### ISSUE TITLE
Unable to create runbook or publish from the extension

### ISSUE THREAD

**Issue by xlandhenry** [microsoft/vscode-azureAutomation#57]
Does this occur consistently? **Yes**
Repro steps:

Action: automation.createRunbook
Error type: Error
Error Message: Request failed with status code 401

Version: 1.2.4
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.85.2
Language: en

<details>
<summary>Call Stack</summary>

```
e.exports extension.js:2:1324995
e.exports extension.js:2:1327411
IncomingMessage.<anonymous> extension.js:2:1318048
```

</details>

**I can delete existing runbooks from the extension though.**

**Comment by Shruti-MS** [comment]
@xlandhenry is the problem in creating all type of runbooks, or any specific.
And can you please check if problem is with specific extension version.

**Comment by xlandhenry** [comment]
> @xlandhenry is the problem in creating all type of runbooks, or any specific. And can you please check if problem is with specific extension version.

Yes the problem is in creating all types of runbooks, powershell, powershell72, python...

I have tried installing an older version of the extension(1.2.1) and can confirm the problem is in both versions.

**Comment by Shruti-MS** [comment]
@xlandhenry I was able to repro the issue. You have to ensure the Azure Configuration is set to ADAL.
you can set this from settings---> Azure configuration
![image](https://github.com/microsoft/vscode-azureAutomation/assets/113353476/c7ec6958-38ba-4092-8086-17ac6274d574)


Please let me know if issue is resolved.

**Comment by xlandhenry** [comment]
Thanks I changed the extension settings to use ADAL and now I can successfully create runbooks.

However as far as I understand ADAL is being deprecated, is MSAL support being developed for this extension?
https://learn.microsoft.com/en-us/entra/identity-platform/msal-migration

**Comment by Shruti-MS** [comment]
Yes, we are working on support of MSAL in extension.
Thanks
