### ISSUE TITLE
can not run automation job

### ISSUE THREAD

**Issue by quockhanh0212** [microsoft/vscode-azureAutomation#64]
Does this occur consistently? 
Repro steps:

1.
2.

Action: automation.startJob
Error type: 429
Error Message: You have reached the limit of allowed JobsByName API calls. Please retry after 8/10/redacted:id redacted:id PM UTC

Version: 1.2.5
OS: darwin
OS Release: 23.6.0
Product: Visual Studio Code
Product Version: 1.92.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.js:2:748185
extension.js:2:748908
```

</details>

**Comment by Shruti-MS** [comment]
@quockhanh0212 the issue is not with extension. No of jobs that you can trigger from automation account reached its limit. 

Thanks for your support. Please open issue if it is not resolved.
